import type { Metadata } from "next";
import { Roboto, Roboto_Serif } from "next/font/google";
import "./globals.css";
import '@szhsin/react-menu/dist/index.css';
import '@szhsin/react-menu/dist/transitions/zoom.css';
import { GlobalDataProvider } from "@/context/globalContext";
import NavBar from "./_components/NavBar/Navbar";
import { AuthCtxProvider } from "@/context/AuthContext";



const roboto_sans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const roboto_serif = Roboto_Serif({
  variable: "--font-roboto-serif",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto_sans.variable} ${roboto_serif.variable} antialiased`}
      >
        <AuthCtxProvider>
          <GlobalDataProvider>
            <NavBar />
            {children}
          </GlobalDataProvider>
        </AuthCtxProvider>
      </body>
    </html>
  );
}
